/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum ColorMode {
  Color = 0,
  Binary = 1
}
export const enum Hierarchical {
  Stacked = 0,
  Cutout = 1
}
export const enum PathSimplifyMode {
  None = 0,
  Polygon = 1,
  Spline = 2
}
export const enum Preset {
  Bw = 0,
  Poster = 1,
  Photo = 2
}
export interface Config {
  colorMode: ColorMode
  hierarchical: Hierarchical
  filterSpeckle: number
  colorPrecision: number
  layerDifference: number
  mode: PathSimplifyMode
  cornerThreshold: number
  lengthThreshold: number
  maxIterations: number
  spliceThreshold: number
  pathPrecision?: number
  width: number
  height: number
}
export function vectorize(source: Buffer, config: Config): Promise<string>
export function vectorizeSync(source: Buffer, config: Config): string
