/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class SvgFile {
  constructor(width: number, height: number, pathPrecision?: number | undefined | null);
  get width(): number;
  get height(): number;
  get pathPrecision(): number | null;
  get pathCount(): number;
  toString(): string;
}
export type JsSvgFile = SvgFile;

export interface Color {
  r: number;
  g: number;
  b: number;
  a?: number;
}

export declare function colorExistsInImage(img: ImageData, color: Color): boolean;

export declare enum ColorMode {
  Color = 0,
  Binary = 1,
}

export interface Config {
  /** True color image or binary image (black and white) */
  colorMode: ColorMode;
  /** Hierarchial clustering or non-stacked. Only applicable to color images. */
  hierarchical: Hierarchical;
  /** Discard patches smaller than X pixels in size (cleaner) */
  filterSpeckle: number;
  /** The number of significant bits to use in an RGB channel (more accurate) */
  colorPrecision: number;
  /** The color difference between gradient layers (less layers) */
  layerDifference: number;
  /** Curve fitting mode */
  mode: PathSimplifyMode;
  /** Minimum momentary angle (degree) to be considered a corner (smoother) */
  cornerThreshold: number;
  /** Perform iterative subdivide smooth until all segments are shorter than this length */
  lengthThreshold: number;
  /** The maximum number of iterations to perform */
  maxIterations: number;
  /** Minimum angle displacement (degree) to splice a spline (less accurate) */
  spliceThreshold: number;
  /** Number of decimal places to use in path string */
  pathPrecision?: number;
  /** Random color search attempts after the reserved key colors are exhausted */
  unusedColorIterations?: number;
  /** Transparent boundary fraction required before keying is applied */
  keyingThreshold?: number;
  /** Maximum cluster bounds treated as a small circle in spline mode */
  smallCircle?: number;
}

export declare function findUnusedColorInImage(img: ImageData, options?: InternalOptions | undefined | null): Color;

export declare enum Hierarchical {
  Stacked = 0,
  Cutout = 1,
}

export interface ImageData {
  width: number;
  height: number;
  pixels: Buffer;
}

export interface InternalOptions {
  unusedColorIterations?: number;
}

export declare enum PathSimplifyMode {
  None = 0,
  Polygon = 1,
  Spline = 2,
}

export declare enum Preset {
  Bw = 0,
  Poster = 1,
  Photo = 2,
}

export interface RawDataConfig {
  width: number;
  height: number;
}

export declare function readImage(source: Buffer, args?: RawDataConfig | undefined | null): ImageData;

export declare function vectorize(source: Buffer, config?: Config | Preset | undefined | null): Promise<string>;

export declare function vectorizeRaw(
  source: Buffer,
  args: RawDataConfig,
  config?: Config | Preset | undefined | null,
): Promise<string>;

export declare function vectorizeRawSync(
  source: Buffer,
  args: RawDataConfig,
  config?: Config | Preset | undefined | null,
): string;

export declare function vectorizeRawToCallback(
  source: Buffer,
  args: RawDataConfig,
  config: Config | Preset | undefined | null,
  callback: ([string, number]) => void,
): Promise<void>;

export declare function vectorizeSync(source: Buffer, config?: Config | Preset | undefined | null): string;

export declare function vectorizeToCallback(
  source: Buffer,
  config: Config | Preset | undefined | null,
  callback: ([string, number]) => void,
): Promise<void>;
