// Based on https://github.com/visioncortex/vtracer/blob/74f2a04a17d8c246d80c439fb162780160a7c3e9/cmdapp/src/svg.rs

use std::fmt::{self, Write};
use visioncortex::{Color, CompoundPath, PointF64};

pub struct SvgFile {
  pub paths: Vec<SvgPath>,
  pub width: usize,
  pub height: usize,
  pub path_precision: Option<u32>,
}

pub struct SvgPath {
  pub path: CompoundPath,
  pub color: Color,
}

impl SvgFile {
  pub fn new(width: usize, height: usize, path_precision: Option<u32>) -> Self {
    Self::with_capacity(width, height, path_precision, 0)
  }

  pub fn with_capacity(
    width: usize,
    height: usize,
    path_precision: Option<u32>,
    capacity: usize,
  ) -> Self {
    SvgFile {
      paths: Vec::with_capacity(capacity),
      width,
      height,
      path_precision,
    }
  }

  pub fn add_path(&mut self, path: CompoundPath, color: Color) {
    self.paths.push(SvgPath { path, color })
  }

  pub fn to_string(&self) -> Result<String, fmt::Error> {
    let mut output = String::with_capacity(128 + self.paths.len() * 128);
    self.write_chunks(|chunk, _progress| {
      output.push_str(&chunk);
      Ok(())
    })?;
    Ok(output)
  }

  pub fn write_chunks<E, F>(&self, mut write: F) -> Result<(), E>
  where
    F: FnMut(String, f64) -> Result<(), E>,
  {
    let total = self.paths.len();
    write(
      String::from("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"),
      0.0,
    )?;
    write(
      String::from("<!-- Generated by @neplex/vectorizer (Using visioncortex VTracer) -->\n"),
      0.0,
    )?;
    write(
      format!(
        "<svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" width=\"{}\" height=\"{}\">\n",
        self.width, self.height
      ),
      0.0,
    )?;
    for (i, path) in self.paths.iter().enumerate() {
      let progress = if total > 0 {
        ((i + 1) as f64 / total as f64 * 100.0).min(100.0)
      } else {
        100.0
      };
      write(path.to_string_with_precision(self.path_precision), progress)?;
    }
    write(String::from("</svg>\n"), 100.0)
  }
}

impl fmt::Display for SvgFile {
  fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    self.write_chunks(|chunk, _progress| f.write_str(&chunk))
  }
}

impl fmt::Display for SvgPath {
  fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    self.fmt_with_precision(f, None)
  }
}

impl SvgPath {
  fn fmt_with_precision(&self, f: &mut fmt::Formatter, precision: Option<u32>) -> fmt::Result {
    f.write_str(&self.to_string_with_precision(precision))
  }

  pub fn to_string_with_precision(&self, precision: Option<u32>) -> String {
    let (string, offset) = self
      .path
      .to_svg_string(true, PointF64::default(), precision);
    let color = self.color.to_hex_string();
    let mut output = String::with_capacity(string.len() + color.len() + 48);
    output.push_str("<path d=\"");
    output.push_str(&string);
    output.push_str("\" fill=\"");
    output.push_str(&color);
    output.push_str("\" transform=\"translate(");
    write!(output, "{},{}", offset.x, offset.y)
      .expect("writing numeric values to String should not fail");
    output.push_str(")\"/>\n");
    output
  }
}
